Migrate to scheduler API #71
enonic/app-snapshotter pull request #147
Opened 2023-05-16 15:06 UTC by ashklianko

2023-05-16 20:14 UTC, rymsha requested changes

2023-05-16 20:14 UTC, rymsha commented on src/main/resources/main.js
> +snapshotsToSchedule.forEach(function (schedule) {
If should be wrapped in isMaster

2023-05-16 20:14 UTC, rymsha commented on src/main/resources/tasks/clean/clean.js
> +    if (libs.cluster.isMaster()) {
Ismaster will prevent jobs to run correctly as job is guaranteed to run on one node but not guaranteed to run on master

2023-05-23 11:10 UTC, ashklianko commented on src/main/resources/main.js
> +snapshotsToSchedule.forEach(function (schedule) {
Updated

2023-05-23 13:45 UTC, rymsha requested changes

2023-05-23 13:45 UTC, rymsha commented on src/main/resources/lib/snapshot-job-scheduler.js
> +    const cleanupCron = libs.configParser.parseCleanupCron(appConfig);
ismaster is missing

2023-05-23 13:45 UTC, rymsha commented on src/main/resources/tasks/snapshot/snapshot.js
> +        if (libs.cluster.isMaster()) {
```suggestion

```

2023-05-23 20:13 UTC, rymsha approved these changes

2023-05-24 06:51 UTC, anatol-sialitski approved these changes

2023-05-24 12:56 UTC, vbradnitski approved these changes

2023-05-29 16:59 UTC, alansemenov approved these changes

2023-05-29 16:59 UTC, merged